[package]
name = "nrv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nrv"
path = "src/main.rs"

[dev-dependencies]
cucumber = { version = "0.20", features = ["macros"] }
tokio = { version = "1.39", features = ["macros", "rt", "rt-multi-thread"] }
